### ISSUE TITLE
Does it support Linux as a service?

### ISSUE THREAD

**Issue by Country-If** [DominikPeters/texpresso-vscode#6]
I can use Texpresso on my Ubuntu server.  Now I wanna know whether I can use my Ubuntu server as a service and allow VsCode on Windows to use this service. I am confused about configuring the Path to the Texpresso binary when I want to access the binary file on the Ubuntu server.

**Comment by DominikPeters** [comment]
I'm not familiar with this setup. You need to put whatever path you need to enter in the Windows command line in order to start texpresso into the "path to texpresso" setting so the extension can call it.
